var user = {
    loggedIn: false,
  first: undefined,
  last: undefined,
  username: undefined,
  pass: undefined,
  email: undefined,
  url: undefined,
  method: undefined,
  google: undefined,
  facebook: undefined,
  sign: undefined,
  city: undefined,
    birthday: undefined,
    meme: undefined,
    background: undefined,
  preferredUnit: undefined,
};
